//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 01:34:55 PM EET 
//


package blog;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="namespaceprefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="officialname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="englishname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="websiteurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logourl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactemail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datasourcetype" type="{http://namespace.openaire.eu/oaf}controlledElementType"/>
 *         &lt;element name="openairecompatibility" type="{http://namespace.openaire.eu/oaf}controlledElementType"/>
 *         &lt;element name="dateofvalidation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subjects" type="{http://namespace.openaire.eu/oaf}typedElementType"/>
 *         &lt;element name="originalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collectedfrom" type="{http://namespace.openaire.eu/oaf}namedIdElementType"/>
 *         &lt;element name="pid" type="{http://namespace.openaire.eu/oaf}typedElementType"/>
 *         &lt;element name="rels" type="{http://namespace.openaire.eu/oaf}relsType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namespaceprefixOrOfficialnameOrEnglishname"
})
@XmlRootElement(name = "datasource")
public class Datasource {

    @XmlElementRefs({
        @XmlElementRef(name = "collectedfrom", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "websiteurl", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "originalId", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datasourcetype", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contactemail", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "longitude", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "englishname", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subjects", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "latitude", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dateofvalidation", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rels", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "officialname", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "openairecompatibility", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pid", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "namespaceprefix", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "logourl", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> namespaceprefixOrOfficialnameOrEnglishname;

    /**
     * Gets the value of the namespaceprefixOrOfficialnameOrEnglishname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namespaceprefixOrOfficialnameOrEnglishname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamespaceprefixOrOfficialnameOrEnglishname().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getNamespaceprefixOrOfficialnameOrEnglishname() {
        if (namespaceprefixOrOfficialnameOrEnglishname == null) {
            namespaceprefixOrOfficialnameOrEnglishname = new ArrayList<JAXBElement<?>>();
        }
        return this.namespaceprefixOrOfficialnameOrEnglishname;
    }

}
