//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 01:34:55 PM EET 
//


package blog;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the blog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResultEmbargoenddate_QNAME = new QName("http://namespace.openaire.eu/oaf", "embargoenddate");
    private final static QName _ResultRelevantdate_QNAME = new QName("http://namespace.openaire.eu/oaf", "relevantdate");
    private final static QName _ResultJournal_QNAME = new QName("http://namespace.openaire.eu/oaf", "journal");
    private final static QName _ResultCitations_QNAME = new QName("http://namespace.openaire.eu/oaf", "citations");
    private final static QName _ResultTitle_QNAME = new QName("http://namespace.openaire.eu/oaf", "title");
    private final static QName _ResultRels_QNAME = new QName("http://namespace.openaire.eu/oaf", "rels");
    private final static QName _ResultDescription_QNAME = new QName("http://namespace.openaire.eu/oaf", "description");
    private final static QName _ResultSource_QNAME = new QName("http://namespace.openaire.eu/oaf", "source");
    private final static QName _ResultLastmetadataupdate_QNAME = new QName("http://namespace.openaire.eu/oaf", "lastmetadataupdate");
    private final static QName _ResultPid_QNAME = new QName("http://namespace.openaire.eu/oaf", "pid");
    private final static QName _ResultLanguage_QNAME = new QName("http://namespace.openaire.eu/oaf", "language");
    private final static QName _ResultInstances_QNAME = new QName("http://namespace.openaire.eu/oaf", "instances");
    private final static QName _ResultDateofacceptance_QNAME = new QName("http://namespace.openaire.eu/oaf", "dateofacceptance");
    private final static QName _ResultMetadataversionnumber_QNAME = new QName("http://namespace.openaire.eu/oaf", "metadataversionnumber");
    private final static QName _ResultSubject_QNAME = new QName("http://namespace.openaire.eu/oaf", "subject");
    private final static QName _ResultCountry_QNAME = new QName("http://namespace.openaire.eu/oaf", "country");
    private final static QName _ResultDevice_QNAME = new QName("http://namespace.openaire.eu/oaf", "device");
    private final static QName _ResultPublisher_QNAME = new QName("http://namespace.openaire.eu/oaf", "publisher");
    private final static QName _ResultOriginalId_QNAME = new QName("http://namespace.openaire.eu/oaf", "originalId");
    private final static QName _ResultSize_QNAME = new QName("http://namespace.openaire.eu/oaf", "size");
    private final static QName _ResultResourcetype_QNAME = new QName("http://namespace.openaire.eu/oaf", "resourcetype");
    private final static QName _ResultVersion_QNAME = new QName("http://namespace.openaire.eu/oaf", "version");
    private final static QName _ResultCommunity_QNAME = new QName("http://namespace.openaire.eu/oaf", "community");
    private final static QName _ResultResulttype_QNAME = new QName("http://namespace.openaire.eu/oaf", "resulttype");
    private final static QName _ResultFormat_QNAME = new QName("http://namespace.openaire.eu/oaf", "format");
    private final static QName _ResultCollectedfrom_QNAME = new QName("http://namespace.openaire.eu/oaf", "collectedfrom");
    private final static QName _ResultBestlicense_QNAME = new QName("http://namespace.openaire.eu/oaf", "bestlicense");
    private final static QName _DatasourceLongitude_QNAME = new QName("http://namespace.openaire.eu/oaf", "longitude");
    private final static QName _DatasourceOfficialname_QNAME = new QName("http://namespace.openaire.eu/oaf", "officialname");
    private final static QName _DatasourceOpenairecompatibility_QNAME = new QName("http://namespace.openaire.eu/oaf", "openairecompatibility");
    private final static QName _DatasourceNamespaceprefix_QNAME = new QName("http://namespace.openaire.eu/oaf", "namespaceprefix");
    private final static QName _DatasourceWebsiteurl_QNAME = new QName("http://namespace.openaire.eu/oaf", "websiteurl");
    private final static QName _DatasourceEnglishname_QNAME = new QName("http://namespace.openaire.eu/oaf", "englishname");
    private final static QName _DatasourceLogourl_QNAME = new QName("http://namespace.openaire.eu/oaf", "logourl");
    private final static QName _DatasourceLatitude_QNAME = new QName("http://namespace.openaire.eu/oaf", "latitude");
    private final static QName _DatasourceSubjects_QNAME = new QName("http://namespace.openaire.eu/oaf", "subjects");
    private final static QName _DatasourceDatasourcetype_QNAME = new QName("http://namespace.openaire.eu/oaf", "datasourcetype");
    private final static QName _DatasourceContactemail_QNAME = new QName("http://namespace.openaire.eu/oaf", "contactemail");
    private final static QName _DatasourceDateofvalidation_QNAME = new QName("http://namespace.openaire.eu/oaf", "dateofvalidation");
    private final static QName _PersonSecondnames_QNAME = new QName("http://namespace.openaire.eu/oaf", "secondnames");
    private final static QName _PersonFullname_QNAME = new QName("http://namespace.openaire.eu/oaf", "fullname");
    private final static QName _PersonNationality_QNAME = new QName("http://namespace.openaire.eu/oaf", "nationality");
    private final static QName _PersonFirstname_QNAME = new QName("http://namespace.openaire.eu/oaf", "firstname");
    private final static QName _OrganizationLegalshortname_QNAME = new QName("http://namespace.openaire.eu/oaf", "legalshortname");
    private final static QName _OrganizationLegalname_QNAME = new QName("http://namespace.openaire.eu/oaf", "legalname");
    private final static QName _ProjectContracttype_QNAME = new QName("http://namespace.openaire.eu/oaf", "contracttype");
    private final static QName _ProjectEcsc39_QNAME = new QName("http://namespace.openaire.eu/oaf", "ecsc39");
    private final static QName _ProjectDuration_QNAME = new QName("http://namespace.openaire.eu/oaf", "duration");
    private final static QName _ProjectEnddate_QNAME = new QName("http://namespace.openaire.eu/oaf", "enddate");
    private final static QName _ProjectStartdate_QNAME = new QName("http://namespace.openaire.eu/oaf", "startdate");
    private final static QName _ProjectFundingtree_QNAME = new QName("http://namespace.openaire.eu/oaf", "fundingtree");
    private final static QName _ProjectEcarticle293_QNAME = new QName("http://namespace.openaire.eu/oaf", "ecarticle29_3");
    private final static QName _ProjectAcronym_QNAME = new QName("http://namespace.openaire.eu/oaf", "acronym");
    private final static QName _ProjectKeywords_QNAME = new QName("http://namespace.openaire.eu/oaf", "keywords");
    private final static QName _ProjectCallidentifier_QNAME = new QName("http://namespace.openaire.eu/oaf", "callidentifier");
    private final static QName _ProjectOamandatepublications_QNAME = new QName("http://namespace.openaire.eu/oaf", "oamandatepublications");
    private final static QName _ProjectCode_QNAME = new QName("http://namespace.openaire.eu/oaf", "code");
    private final static QName _RelTypeFax_QNAME = new QName("http://namespace.openaire.eu/oaf", "fax");
    private final static QName _RelTypeEmail_QNAME = new QName("http://namespace.openaire.eu/oaf", "email");
    private final static QName _RelTypeTo_QNAME = new QName("http://namespace.openaire.eu/oaf", "to");
    private final static QName _RelTypeRanking_QNAME = new QName("http://namespace.openaire.eu/oaf", "ranking");
    private final static QName _RelTypePhone_QNAME = new QName("http://namespace.openaire.eu/oaf", "phone");
    private final static QName _RelTypeSimilarity_QNAME = new QName("http://namespace.openaire.eu/oaf", "similarity");
    private final static QName _RelTypeType_QNAME = new QName("http://namespace.openaire.eu/oaf", "type");
    private final static QName _RelTypeFunding_QNAME = new QName("http://namespace.openaire.eu/oaf", "funding");
    private final static QName _FundingTreeTypeFundingLevel0_QNAME = new QName("http://namespace.openaire.eu/oaf", "funding_level_0");
    private final static QName _FundingTreeTypeFundingLevel1_QNAME = new QName("http://namespace.openaire.eu/oaf", "funding_level_1");
    private final static QName _FundingTreeTypeFundingLevel2_QNAME = new QName("http://namespace.openaire.eu/oaf", "funding_level_2");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: blog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CitationsType }
     * 
     */
    public CitationsType createCitationsType() {
        return new CitationsType();
    }

    /**
     * Create an instance of {@link CitationsType.Citation }
     * 
     */
    public CitationsType.Citation createCitationsTypeCitation() {
        return new CitationsType.Citation();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link TypedElementType }
     * 
     */
    public TypedElementType createTypedElementType() {
        return new TypedElementType();
    }

    /**
     * Create an instance of {@link ControlledElementType }
     * 
     */
    public ControlledElementType createControlledElementType() {
        return new ControlledElementType();
    }

    /**
     * Create an instance of {@link JournalType }
     * 
     */
    public JournalType createJournalType() {
        return new JournalType();
    }

    /**
     * Create an instance of {@link NamedIdElementType }
     * 
     */
    public NamedIdElementType createNamedIdElementType() {
        return new NamedIdElementType();
    }

    /**
     * Create an instance of {@link CommunityType }
     * 
     */
    public CommunityType createCommunityType() {
        return new CommunityType();
    }

    /**
     * Create an instance of {@link RelsType }
     * 
     */
    public RelsType createRelsType() {
        return new RelsType();
    }

    /**
     * Create an instance of {@link InstancesType }
     * 
     */
    public InstancesType createInstancesType() {
        return new InstancesType();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Datasource }
     * 
     */
    public Datasource createDatasource() {
        return new Datasource();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link FundingTreeType }
     * 
     */
    public FundingTreeType createFundingTreeType() {
        return new FundingTreeType();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link RelToType }
     * 
     */
    public RelToType createRelToType() {
        return new RelToType();
    }

    /**
     * Create an instance of {@link WebresourceType }
     * 
     */
    public WebresourceType createWebresourceType() {
        return new WebresourceType();
    }

    /**
     * Create an instance of {@link ConceptType }
     * 
     */
    public ConceptType createConceptType() {
        return new ConceptType();
    }

    /**
     * Create an instance of {@link FunderFlatType }
     * 
     */
    public FunderFlatType createFunderFlatType() {
        return new FunderFlatType();
    }

    /**
     * Create an instance of {@link RelType }
     * 
     */
    public RelType createRelType() {
        return new RelType();
    }

    /**
     * Create an instance of {@link NamedFundingLevel }
     * 
     */
    public NamedFundingLevel createNamedFundingLevel() {
        return new NamedFundingLevel();
    }

    /**
     * Create an instance of {@link FunderType }
     * 
     */
    public FunderType createFunderType() {
        return new FunderType();
    }

    /**
     * Create an instance of {@link ExternalreferenceType }
     * 
     */
    public ExternalreferenceType createExternalreferenceType() {
        return new ExternalreferenceType();
    }

    /**
     * Create an instance of {@link InferenceExtendedStringType }
     * 
     */
    public InferenceExtendedStringType createInferenceExtendedStringType() {
        return new InferenceExtendedStringType();
    }

    /**
     * Create an instance of {@link FundingFlatType }
     * 
     */
    public FundingFlatType createFundingFlatType() {
        return new FundingFlatType();
    }

    /**
     * Create an instance of {@link FundingType }
     * 
     */
    public FundingType createFundingType() {
        return new FundingType();
    }

    /**
     * Create an instance of {@link InstanceType }
     * 
     */
    public InstanceType createInstanceType() {
        return new InstanceType();
    }

    /**
     * Create an instance of {@link LabeledIdElementType }
     * 
     */
    public LabeledIdElementType createLabeledIdElementType() {
        return new LabeledIdElementType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link FundingParentType }
     * 
     */
    public FundingParentType createFundingParentType() {
        return new FundingParentType();
    }

    /**
     * Create an instance of {@link InferenceExtendedBooleanType }
     * 
     */
    public InferenceExtendedBooleanType createInferenceExtendedBooleanType() {
        return new InferenceExtendedBooleanType();
    }

    /**
     * Create an instance of {@link CitationsType.Citation.Id }
     * 
     */
    public CitationsType.Citation.Id createCitationsTypeCitationId() {
        return new CitationsType.Citation.Id();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "embargoenddate", scope = Result.class)
    public JAXBElement<String> createResultEmbargoenddate(String value) {
        return new JAXBElement<String>(_ResultEmbargoenddate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "relevantdate", scope = Result.class)
    public JAXBElement<String> createResultRelevantdate(String value) {
        return new JAXBElement<String>(_ResultRelevantdate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JournalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "journal", scope = Result.class)
    public JAXBElement<JournalType> createResultJournal(JournalType value) {
        return new JAXBElement<JournalType>(_ResultJournal_QNAME, JournalType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CitationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "citations", scope = Result.class)
    public JAXBElement<CitationsType> createResultCitations(CitationsType value) {
        return new JAXBElement<CitationsType>(_ResultCitations_QNAME, CitationsType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "title", scope = Result.class)
    public JAXBElement<String> createResultTitle(String value) {
        return new JAXBElement<String>(_ResultTitle_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Result.class)
    public JAXBElement<RelsType> createResultRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "description", scope = Result.class)
    public JAXBElement<String> createResultDescription(String value) {
        return new JAXBElement<String>(_ResultDescription_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "source", scope = Result.class)
    public JAXBElement<String> createResultSource(String value) {
        return new JAXBElement<String>(_ResultSource_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "lastmetadataupdate", scope = Result.class)
    public JAXBElement<String> createResultLastmetadataupdate(String value) {
        return new JAXBElement<String>(_ResultLastmetadataupdate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Result.class)
    public JAXBElement<TypedElementType> createResultPid(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_ResultPid_QNAME, TypedElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "language", scope = Result.class)
    public JAXBElement<ControlledElementType> createResultLanguage(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_ResultLanguage_QNAME, ControlledElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstancesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "instances", scope = Result.class)
    public JAXBElement<InstancesType> createResultInstances(InstancesType value) {
        return new JAXBElement<InstancesType>(_ResultInstances_QNAME, InstancesType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "dateofacceptance", scope = Result.class)
    public JAXBElement<String> createResultDateofacceptance(String value) {
        return new JAXBElement<String>(_ResultDateofacceptance_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "metadataversionnumber", scope = Result.class)
    public JAXBElement<String> createResultMetadataversionnumber(String value) {
        return new JAXBElement<String>(_ResultMetadataversionnumber_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "subject", scope = Result.class)
    public JAXBElement<TypedElementType> createResultSubject(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_ResultSubject_QNAME, TypedElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "country", scope = Result.class)
    public JAXBElement<ControlledElementType> createResultCountry(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_ResultCountry_QNAME, ControlledElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "device", scope = Result.class)
    public JAXBElement<String> createResultDevice(String value) {
        return new JAXBElement<String>(_ResultDevice_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "publisher", scope = Result.class)
    public JAXBElement<String> createResultPublisher(String value) {
        return new JAXBElement<String>(_ResultPublisher_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Result.class)
    public JAXBElement<String> createResultOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "size", scope = Result.class)
    public JAXBElement<String> createResultSize(String value) {
        return new JAXBElement<String>(_ResultSize_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "resourcetype", scope = Result.class)
    public JAXBElement<String> createResultResourcetype(String value) {
        return new JAXBElement<String>(_ResultResourcetype_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "version", scope = Result.class)
    public JAXBElement<String> createResultVersion(String value) {
        return new JAXBElement<String>(_ResultVersion_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "community", scope = Result.class)
    public JAXBElement<CommunityType> createResultCommunity(CommunityType value) {
        return new JAXBElement<CommunityType>(_ResultCommunity_QNAME, CommunityType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "resulttype", scope = Result.class)
    public JAXBElement<String> createResultResulttype(String value) {
        return new JAXBElement<String>(_ResultResulttype_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "format", scope = Result.class)
    public JAXBElement<String> createResultFormat(String value) {
        return new JAXBElement<String>(_ResultFormat_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Result.class)
    public JAXBElement<NamedIdElementType> createResultCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "bestlicense", scope = Result.class)
    public JAXBElement<ControlledElementType> createResultBestlicense(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_ResultBestlicense_QNAME, ControlledElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "longitude", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLongitude(String value) {
        return new JAXBElement<String>(_DatasourceLongitude_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "officialname", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOfficialname(String value) {
        return new JAXBElement<String>(_DatasourceOfficialname_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "openairecompatibility", scope = Datasource.class)
    public JAXBElement<ControlledElementType> createDatasourceOpenairecompatibility(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_DatasourceOpenairecompatibility_QNAME, ControlledElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "namespaceprefix", scope = Datasource.class)
    public JAXBElement<String> createDatasourceNamespaceprefix(String value) {
        return new JAXBElement<String>(_DatasourceNamespaceprefix_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "websiteurl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceWebsiteurl(String value) {
        return new JAXBElement<String>(_DatasourceWebsiteurl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "englishname", scope = Datasource.class)
    public JAXBElement<String> createDatasourceEnglishname(String value) {
        return new JAXBElement<String>(_DatasourceEnglishname_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Datasource.class)
    public JAXBElement<RelsType> createDatasourceRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "logourl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLogourl(String value) {
        return new JAXBElement<String>(_DatasourceLogourl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "description", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDescription(String value) {
        return new JAXBElement<String>(_ResultDescription_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Datasource.class)
    public JAXBElement<NamedIdElementType> createDatasourceCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Datasource.class)
    public JAXBElement<TypedElementType> createDatasourcePid(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_ResultPid_QNAME, TypedElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "latitude", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLatitude(String value) {
        return new JAXBElement<String>(_DatasourceLatitude_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "subjects", scope = Datasource.class)
    public JAXBElement<TypedElementType> createDatasourceSubjects(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_DatasourceSubjects_QNAME, TypedElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "datasourcetype", scope = Datasource.class)
    public JAXBElement<ControlledElementType> createDatasourceDatasourcetype(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_DatasourceDatasourcetype_QNAME, ControlledElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "contactemail", scope = Datasource.class)
    public JAXBElement<String> createDatasourceContactemail(String value) {
        return new JAXBElement<String>(_DatasourceContactemail_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "dateofvalidation", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDateofvalidation(String value) {
        return new JAXBElement<String>(_DatasourceDateofvalidation_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Person.class)
    public JAXBElement<RelsType> createPersonRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "secondnames", scope = Person.class)
    public JAXBElement<String> createPersonSecondnames(String value) {
        return new JAXBElement<String>(_PersonSecondnames_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Person.class)
    public JAXBElement<NamedIdElementType> createPersonCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "fullname", scope = Person.class)
    public JAXBElement<String> createPersonFullname(String value) {
        return new JAXBElement<String>(_PersonFullname_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Person.class)
    public JAXBElement<String> createPersonOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Person.class)
    public JAXBElement<TypedElementType> createPersonPid(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_ResultPid_QNAME, TypedElementType.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "nationality", scope = Person.class)
    public JAXBElement<ControlledElementType> createPersonNationality(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_PersonNationality_QNAME, ControlledElementType.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "firstname", scope = Person.class)
    public JAXBElement<String> createPersonFirstname(String value) {
        return new JAXBElement<String>(_PersonFirstname_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Organization.class)
    public JAXBElement<RelsType> createOrganizationRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "logourl", scope = Organization.class)
    public JAXBElement<String> createOrganizationLogourl(String value) {
        return new JAXBElement<String>(_DatasourceLogourl_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Organization.class)
    public JAXBElement<NamedIdElementType> createOrganizationCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Organization.class)
    public JAXBElement<String> createOrganizationOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Organization.class)
    public JAXBElement<TypedElementType> createOrganizationPid(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_ResultPid_QNAME, TypedElementType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalshortname", scope = Organization.class)
    public JAXBElement<String> createOrganizationLegalshortname(String value) {
        return new JAXBElement<String>(_OrganizationLegalshortname_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalname", scope = Organization.class)
    public JAXBElement<String> createOrganizationLegalname(String value) {
        return new JAXBElement<String>(_OrganizationLegalname_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "websiteurl", scope = Organization.class)
    public JAXBElement<String> createOrganizationWebsiteurl(String value) {
        return new JAXBElement<String>(_DatasourceWebsiteurl_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "country", scope = Organization.class)
    public JAXBElement<ControlledElementType> createOrganizationCountry(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_ResultCountry_QNAME, ControlledElementType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Project.class)
    public JAXBElement<String> createProjectOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "contracttype", scope = Project.class)
    public JAXBElement<ControlledElementType> createProjectContracttype(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_ProjectContracttype_QNAME, ControlledElementType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "websiteurl", scope = Project.class)
    public JAXBElement<String> createProjectWebsiteurl(String value) {
        return new JAXBElement<String>(_DatasourceWebsiteurl_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "ecsc39", scope = Project.class)
    public JAXBElement<String> createProjectEcsc39(String value) {
        return new JAXBElement<String>(_ProjectEcsc39_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "duration", scope = Project.class)
    public JAXBElement<String> createProjectDuration(String value) {
        return new JAXBElement<String>(_ProjectDuration_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "enddate", scope = Project.class)
    public JAXBElement<String> createProjectEnddate(String value) {
        return new JAXBElement<String>(_ProjectEnddate_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "title", scope = Project.class)
    public JAXBElement<String> createProjectTitle(String value) {
        return new JAXBElement<String>(_ResultTitle_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "startdate", scope = Project.class)
    public JAXBElement<String> createProjectStartdate(String value) {
        return new JAXBElement<String>(_ProjectStartdate_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Project.class)
    public JAXBElement<RelsType> createProjectRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingTreeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "fundingtree", scope = Project.class)
    public JAXBElement<FundingTreeType> createProjectFundingtree(FundingTreeType value) {
        return new JAXBElement<FundingTreeType>(_ProjectFundingtree_QNAME, FundingTreeType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Project.class)
    public JAXBElement<NamedIdElementType> createProjectCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "ecarticle29_3", scope = Project.class)
    public JAXBElement<String> createProjectEcarticle293(String value) {
        return new JAXBElement<String>(_ProjectEcarticle293_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Project.class)
    public JAXBElement<TypedElementType> createProjectPid(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_ResultPid_QNAME, TypedElementType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "acronym", scope = Project.class)
    public JAXBElement<String> createProjectAcronym(String value) {
        return new JAXBElement<String>(_ProjectAcronym_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "keywords", scope = Project.class)
    public JAXBElement<String> createProjectKeywords(String value) {
        return new JAXBElement<String>(_ProjectKeywords_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "callidentifier", scope = Project.class)
    public JAXBElement<String> createProjectCallidentifier(String value) {
        return new JAXBElement<String>(_ProjectCallidentifier_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "subjects", scope = Project.class)
    public JAXBElement<TypedElementType> createProjectSubjects(TypedElementType value) {
        return new JAXBElement<TypedElementType>(_DatasourceSubjects_QNAME, TypedElementType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "oamandatepublications", scope = Project.class)
    public JAXBElement<Boolean> createProjectOamandatepublications(Boolean value) {
        return new JAXBElement<Boolean>(_ProjectOamandatepublications_QNAME, Boolean.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "code", scope = Project.class)
    public JAXBElement<String> createProjectCode(String value) {
        return new JAXBElement<String>(_ProjectCode_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "fax", scope = RelType.class)
    public JAXBElement<String> createRelTypeFax(String value) {
        return new JAXBElement<String>(_RelTypeFax_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "email", scope = RelType.class)
    public JAXBElement<String> createRelTypeEmail(String value) {
        return new JAXBElement<String>(_RelTypeEmail_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "officialname", scope = RelType.class)
    public JAXBElement<String> createRelTypeOfficialname(String value) {
        return new JAXBElement<String>(_DatasourceOfficialname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "publisher", scope = RelType.class)
    public JAXBElement<String> createRelTypePublisher(String value) {
        return new JAXBElement<String>(_ResultPublisher_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelToType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "to", scope = RelType.class)
    public JAXBElement<RelToType> createRelTypeTo(RelToType value) {
        return new JAXBElement<RelToType>(_RelTypeTo_QNAME, RelToType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "fullname", scope = RelType.class)
    public JAXBElement<String> createRelTypeFullname(String value) {
        return new JAXBElement<String>(_PersonFullname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "ranking", scope = RelType.class)
    public JAXBElement<BigInteger> createRelTypeRanking(BigInteger value) {
        return new JAXBElement<BigInteger>(_RelTypeRanking_QNAME, BigInteger.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "phone", scope = RelType.class)
    public JAXBElement<String> createRelTypePhone(String value) {
        return new JAXBElement<String>(_RelTypePhone_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "contracttype", scope = RelType.class)
    public JAXBElement<ControlledElementType> createRelTypeContracttype(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_ProjectContracttype_QNAME, ControlledElementType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "websiteurl", scope = RelType.class)
    public JAXBElement<Object> createRelTypeWebsiteurl(Object value) {
        return new JAXBElement<Object>(_DatasourceWebsiteurl_QNAME, Object.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "similarity", scope = RelType.class)
    public JAXBElement<Double> createRelTypeSimilarity(Double value) {
        return new JAXBElement<Double>(_RelTypeSimilarity_QNAME, Double.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "title", scope = RelType.class)
    public JAXBElement<String> createRelTypeTitle(String value) {
        return new JAXBElement<String>(_ResultTitle_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "type", scope = RelType.class)
    public JAXBElement<String> createRelTypeType(String value) {
        return new JAXBElement<String>(_RelTypeType_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "resulttype", scope = RelType.class)
    public JAXBElement<String> createRelTypeResulttype(String value) {
        return new JAXBElement<String>(_ResultResulttype_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "acronym", scope = RelType.class)
    public JAXBElement<String> createRelTypeAcronym(String value) {
        return new JAXBElement<String>(_ProjectAcronym_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "dateofacceptance", scope = RelType.class)
    public JAXBElement<String> createRelTypeDateofacceptance(String value) {
        return new JAXBElement<String>(_ResultDateofacceptance_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalshortname", scope = RelType.class)
    public JAXBElement<String> createRelTypeLegalshortname(String value) {
        return new JAXBElement<String>(_OrganizationLegalshortname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalname", scope = RelType.class)
    public JAXBElement<String> createRelTypeLegalname(String value) {
        return new JAXBElement<String>(_OrganizationLegalname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "datasourcetype", scope = RelType.class)
    public JAXBElement<ControlledElementType> createRelTypeDatasourcetype(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_DatasourceDatasourcetype_QNAME, ControlledElementType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlledElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "country", scope = RelType.class)
    public JAXBElement<ControlledElementType> createRelTypeCountry(ControlledElementType value) {
        return new JAXBElement<ControlledElementType>(_ResultCountry_QNAME, ControlledElementType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "code", scope = RelType.class)
    public JAXBElement<String> createRelTypeCode(String value) {
        return new JAXBElement<String>(_ProjectCode_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingFlatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "funding", scope = RelType.class)
    public JAXBElement<FundingFlatType> createRelTypeFunding(FundingFlatType value) {
        return new JAXBElement<FundingFlatType>(_RelTypeFunding_QNAME, FundingFlatType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "funding_level_0", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel0(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel0_QNAME, FundingType.class, FundingTreeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "funding_level_1", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel1(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel1_QNAME, FundingType.class, FundingTreeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "funding_level_2", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel2(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel2_QNAME, FundingType.class, FundingTreeType.class, value);
    }

}
