//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 01:34:55 PM EET 
//


package blog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Journal where the publication has been published. Attributes refer to
 * 				electronic, printed and linking (ISSN-L) ISSN. This field is applicable when
 * 				resulttype is "publication". 
 * 
 * <p>Java class for journalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="journalType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="eissn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="issn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="lissn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "journalType", propOrder = {
    "value"
})
public class JournalType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "eissn")
    @XmlSchemaType(name = "anySimpleType")
    protected String eissn;
    @XmlAttribute(name = "issn")
    @XmlSchemaType(name = "anySimpleType")
    protected String issn;
    @XmlAttribute(name = "lissn")
    @XmlSchemaType(name = "anySimpleType")
    protected String lissn;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the eissn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEissn() {
        return eissn;
    }

    /**
     * Sets the value of the eissn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEissn(String value) {
        this.eissn = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssn() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssn(String value) {
        this.issn = value;
    }

    /**
     * Gets the value of the lissn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLissn() {
        return lissn;
    }

    /**
     * Sets the value of the lissn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLissn(String value) {
        this.lissn = value;
    }

}
